package com.pierlesstech.journal.web;

public enum JournalActions {
	INIT, REGISTER, LOGIN, NEXTDAY, PREVDAY, LOGOUT, SAVE, SEARCH, DATE, SETTING, CHANGESETTING, ADDIMAGE, UPLOADIMAGE, GOOGLELOGIN, DELETEIMAGE, DEBUG, CONTACT, LICENSE, CHANGEACCOUNT
}
